### ISSUE TITLE
[BE] FEAT: 댓글 기능 구현

### ISSUE THREAD

**Issue by nicolao00** [CSID-DGU/2023-1-OSSP2-DALL-E-noway-2#17]
### 작업 설명

꿈일기 피드와 게시글에서 댓글, 답글을 등록, 조회하는 기능을 구현하겠습니다.

### 접근 방법

댓글 조회 

1. 유저가 서버의 /api/comments/:filter-type/:id 엔드포인트로 접근한다.
2. filter_type으로 꿈일기 피드인지, 기타 게시글인지 판별한다.
3. 게시글 타입 판별 후 dream_diary OR board 테이블에서 GET으로 받아온 id값에 맞는 글의 댓글들을 가져온다.

댓글 달기
- 작성란에 댓글을 작성 완료할 시 댓글에 해당하는 정보를 DB에 저장한다. 

답글 달기
- POST를 통해 매개변수로 넘어온 답글의 comment_id를 추출하여 parent_comment_id에 저장한다.
- 그 외 사항은 위 댓글 달기 내용과 동일.

### 대처 방안 (선택 사항)
`
comment table에 댓글 내용이 담길 colum이 없어서 테이블에 content 라는 이름의 colum을 추가해야할 것 같습니다.
`

**Comment by sichoi42** [comment]
> comment table에 body가 없어서 추가해야할 것 같습니다!

헐 그러네요..?!
구현하실 때 DDL에 직접 추가해주시면 감사하겠습니다!
필드명은 다른 테이블과의 통일성을 위해서 content로 하는건 어떨까요?

**Comment by nicolao00** [comment]
넵 좋습니다!

**Comment by nicolao00** [comment]
추가로 댓글 삭제시에 Request가 /api/comments/:filter-type/:id로 되어있는데 
/api/comments/:filter-type/:id/:comment-id로 comment-id도 함께 넘겨주어야 삭제가 가능할 것 같습니다.

**Comment by sichoi42** [comment]
> 추가로 댓글 삭제시에 Request가 /api/comments/:filter-type/:id로 되어있는데 /api/comments/:filter-type/:id/:comment-id로 comment-id도 함께 넘겨주어야 삭제가 가능할 것 같습니다.

엇 이걸 이제 봤네요..? 알겠습니다!!
